# Importando Bibliotecas

In [56]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics.pairwise import cosine_similarity

# Importando Dados

In [18]:
df_order_items = pd.read_csv('DNC_order_items_dataset.csv', index_col=0)
df_order_review = pd.read_csv('DNC_order_reviews_dataset.csv', index_col=0)
df_order_dataset = pd.read_csv('DNC_orders_dataset.csv', index_col=0)
df_products_dataset = pd.read_csv('DNC_products_dataset.csv', index_col=0)
df_products_dataset = df_products_dataset.dropna(axis=0, how='any', thresh=None, subset=None, inplace=False)


# Analisando as Informações

In [19]:
print('Info Order Items')
print(df_order_items.info())
print('                                         ')
print('                                         ')
print('                                         ')
print('Info Order Review')
print(df_order_review.info())
print('                                         ')
print('                                         ')
print('                                         ')
print('Info Order Dataset')
print(df_order_dataset.info())
print('                                         ')
print('                                         ')
print('                                         ')
print('Info Products Dataset')
print(df_products_dataset.info())

Info Order Items
<class 'pandas.core.frame.DataFrame'>
Int64Index: 112650 entries, 0 to 112649
Data columns (total 4 columns):
 #   Column         Non-Null Count   Dtype  
---  ------         --------------   -----  
 0   order_id       112650 non-null  object 
 1   order_item_id  112650 non-null  int64  
 2   product_id     112650 non-null  object 
 3   price          112650 non-null  float64
dtypes: float64(1), int64(1), object(2)
memory usage: 4.3+ MB
None
                                         
                                         
                                         
Info Order Review
<class 'pandas.core.frame.DataFrame'>
Int64Index: 99224 entries, 0 to 99223
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   review_id     99224 non-null  object
 1   order_id      99224 non-null  object
 2   review_score  99224 non-null  int64 
dtypes: int64(1), object(2)
memory usage: 3.0+ MB
None
                   

In [20]:
df_order_items_review = pd.merge(df_order_items,df_order_review, on= 'order_id')

In [21]:
df_order_items_review

order_id  order_item_id  \
0       00010242fe8c5a6d1ba2dd792cb16214              1   
1       00018f77f2f0320c557190d7a144bdd3              1   
2       000229ec398224ef6ca0657da4fc703e              1   
3       00024acbcdf0a6daa1e931b038114c75              1   
4       00042b26cf59d7ce69dfabb4e55b4fd9              1   
...                                  ...            ...   
112367  fffc94f6ce00a00581880bf54a75a037              1   
112368  fffcd46ef2263f404302a634eb57f7eb              1   
112369  fffce4705a9662cd70adb13d4a31832d              1   
112370  fffe18544ffabc95dfada21779c9644f              1   
112371  fffe41c64501cc87c801fd61db3f6244              1   

                              product_id   price  \
0       4244733e06e7ecb4970a6e2683c13e61   58.90   
1       e5f2d52b802189ee658865ca93d83a8f  239.90   
2       c777355d18b72b67abbeef9df44fd0fd  199.00   
3       7634da152a4610f1595efa32f14722fc   12.99   
4       ac6c3623068f30de03045865e4e10089  199.90   
...                                  ...     ...   
112367  4aa6014eceb682077f9dc4bffebc05b0  299.99   
112368  32e07fd915822b0765e448c4dd74c828  350.00   
112369  72a30483855e2eafc67aee5dc2560482   99.90   
112370  9c422a519119dcad7575db5af1ba540e   55.99   
112371  350688d9dc1e75ff97be326363655e01   43.00   

                               review_id  review_score  
0       97ca439bc427b48bc1cd7177abe71365             5  
1       7b07bacd811c4117b742569b04ce3580             4  
2       0c5b33dea94867d1ac402749e5438e8b             5  
3       f4028d019cb58564807486a6aaf33817             4  
4       940144190dcba6351888cafa43f3a3a5             5  
...                                  ...           ...  
112367  9185f849f32d82e216a4e025e0c50f5c             5  
112368  be803f6a93d64719fd685c1cc610918a             5  
112369  dbdd81cd59a1a9f94a10a990b4d48dce             5  
112370  fba117c9ac40d41ca7be54741f471303             5  
112371  b2700869a37f1aafc9dda829dc2f9027             5  

[112372 rows x 6 columns]

In [22]:
df_order = pd.merge(df_order_items_review, df_order_dataset, on='order_id')

In [23]:
df_order.head()

order_id  order_item_id  \
0  00010242fe8c5a6d1ba2dd792cb16214              1   
1  00018f77f2f0320c557190d7a144bdd3              1   
2  000229ec398224ef6ca0657da4fc703e              1   
3  00024acbcdf0a6daa1e931b038114c75              1   
4  00042b26cf59d7ce69dfabb4e55b4fd9              1   

                         product_id   price                         review_id  \
0  4244733e06e7ecb4970a6e2683c13e61   58.90  97ca439bc427b48bc1cd7177abe71365   
1  e5f2d52b802189ee658865ca93d83a8f  239.90  7b07bacd811c4117b742569b04ce3580   
2  c777355d18b72b67abbeef9df44fd0fd  199.00  0c5b33dea94867d1ac402749e5438e8b   
3  7634da152a4610f1595efa32f14722fc   12.99  f4028d019cb58564807486a6aaf33817   
4  ac6c3623068f30de03045865e4e10089  199.90  940144190dcba6351888cafa43f3a3a5   

   review_score                       customer_id order_status  
0             5  3ce436f183e68e07877b285a838db11a    delivered  
1             4  f6dd3ec061db4e3987629fe6b26e5cce    delivered  
2             5  6489ae5e4333f3693df5ad4372dab6d3    delivered  
3             4  d4eb9395c8c0431ee92fce09860c5a06    delivered  
4             5  58dbd0b2d70206bf40e62cd34e84d795    delivered

In [24]:
df_order.order_item_id.unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21], dtype=int64)

In [25]:
df_order.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 112372 entries, 0 to 112371
Data columns (total 8 columns):
 #   Column         Non-Null Count   Dtype  
---  ------         --------------   -----  
 0   order_id       112372 non-null  object 
 1   order_item_id  112372 non-null  int64  
 2   product_id     112372 non-null  object 
 3   price          112372 non-null  float64
 4   review_id      112372 non-null  object 
 5   review_score   112372 non-null  int64  
 6   customer_id    112372 non-null  object 
 7   order_status   112372 non-null  object 
dtypes: float64(1), int64(2), object(5)
memory usage: 7.7+ MB


# Recomendação Simples

In [44]:
df_all = pd.merge(df_order, df_products_dataset, on='product_id')
#df1 = df_order.groupby(['review_id','order_id', 'review_score', 'order_item_id', 'product_id', 'price'] ).first()
df1 = df_all.groupby(['review_id','order_id', 'review_score', 'product_id', 'price', 'customer_id'], as_index=False ).first()
#df1 = df_order.merge(df_itens, on=['order_id'], how='left')
df1.head()

review_id                          order_id  \
0  0001239bc1de2e33cb583967c2ca4c67  fc046d7776171871436844218f817d7d   
1  0001cc6860aeaf5b9017fe4131a52e62  d4665434b01caa9dc3e3e78b3eb3593e   
2  00020c7512a52e92212f12d3e37513c0  e28abf2eb2f1fbcbdc2dd0cd9a561671   
3  00032b0141443497c898b3093690af51  04fb47576993a3cb0c12d4b25eab6e4e   
4  00034d88989f9a4c393bdcaec301537f  5f358d797a49fe2f24352f73426215f6   

   review_score                        product_id   price  \
0             5  461f43be3bdf8844e65b62d9ac2c7a5a  145.00   
1             5  6e7f4ae007302e93c5610894712289bb   60.00   
2             5  a39cc58c1b5926b6f9f378daa89f1315  150.00   
3             5  af51d485dc5255ba2e18b21b550156e6  259.90   
4             5  63d6e7ab30f482382c9dfbbccae7da54   68.89   

                        customer_id  order_item_id order_status  \
0  1458a88f3713f047a6d4a23a8ee0f3e5              1    delivered   
1  430629c51214778912efab67e023a8f1              1    delivered   
2  b1ff51be5960d3ed39bb63679f068555              1    delivered   
3  c158fb97a12041c9305718081a78b064              1    delivered   
4  e44e2e5c3ad690e075b368557195abb7              1    delivered   

  product_category_name  product_name_lenght  product_description_lenght  \
0    relogios_presentes                 35.0                       591.0   
1       fraldas_higiene                 49.0                       154.0   
2       casa_construcao                 53.0                       646.0   
3      malas_acessorios                 57.0                       674.0   
4       eletroportateis                 56.0                      1031.0   

   product_weight_g  product_length_cm  product_height_cm  product_width_cm  
0             444.0               20.0               14.0              16.0  
1            1250.0               20.0               22.0              16.0  
2            3800.0               30.0               35.0              30.0  
3           22350.0               32.0               74.0              53.0  
4             625.0               21.0               19.0              16.0

In [28]:
df_all.head()

order_id  order_item_id  \
0  00010242fe8c5a6d1ba2dd792cb16214              1   
1  130898c0987d1801452a8ed92a670612              1   
2  532ed5e14e24ae1f0d735b91524b98b9              1   
3  6f8c31653edb8c83e1a739408b5ff750              1   
4  7d19f4ef4d04461989632411b7e588b9              1   

                         product_id  price                         review_id  \
0  4244733e06e7ecb4970a6e2683c13e61   58.9  97ca439bc427b48bc1cd7177abe71365   
1  4244733e06e7ecb4970a6e2683c13e61   55.9  b11cba360bbe71410c291b764753d37f   
2  4244733e06e7ecb4970a6e2683c13e61   64.9  af01c4017c5ab46df6cc810e069e654a   
3  4244733e06e7ecb4970a6e2683c13e61   58.9  8304ff37d8b16b57086fa283fe0c44f8   
4  4244733e06e7ecb4970a6e2683c13e61   58.9  426f43a82185969503fb3c86241a9535   

   review_score                       customer_id order_status  \
0             5  3ce436f183e68e07877b285a838db11a    delivered   
1             5  e6eecc5a77de221464d1c4eaff0a9b64    delivered   
2             4  4ef55bf80f711b372afebcb7c715344a    delivered   
3             5  30407a72ad8b3f4df4d15369126b20c9    delivered   
4             5  91a792fef70ecd8cc69d3c7feb3d12da    delivered   

  product_category_name  product_name_lenght  product_description_lenght  \
0            cool_stuff                 58.0                       598.0   
1            cool_stuff                 58.0                       598.0   
2            cool_stuff                 58.0                       598.0   
3            cool_stuff                 58.0                       598.0   
4            cool_stuff                 58.0                       598.0   

   product_weight_g  product_length_cm  product_height_cm  product_width_cm  
0             650.0               28.0                9.0              14.0  
1             650.0               28.0                9.0              14.0  
2             650.0               28.0                9.0              14.0  
3             650.0               28.0                9.0              14.0  
4             650.0               28.0                9.0              14.0

In [45]:
##Recomendando os Produtos com Maiores notas de Review
ratings_explicit_product = df1[df1['review_score'] != 0]

ratings_sum = pd.DataFrame(ratings_explicit_product.groupby(['product_id'])['review_score'].sum())
top1500_product = ratings_sum.sort_values('review_score', ascending = False).head(1500)

top1500_product.merge(df_products_dataset, left_index = True, right_on = 'product_id').head(10)

review_score                        product_id   product_category_name  \
9661           1800  99a4788cb24856965c36a24e339b6058         cama_mesa_banho   
13430          1759  aca2eb7d00ea1a7b8ebd4e68314663af        moveis_decoracao   
14051          1456  422879e10f46682990de24d770e7f83d      ferramentas_jardim   
8290           1355  d1c427060a0f73f6b889a5c7c61f2ac4  informatica_acessorios   
30293          1295  389d119b48cf3043d311335e499d9c6b      ferramentas_jardim   
793            1283  53b36df67ebb7c41585e8d54d6772e08      relogios_presentes   
1749           1209  154e7e31ebfa092203795c972e5804a6            beleza_saude   
4598           1199  368c6c730842d78016ad823897a372db      ferramentas_jardim   
32098          1143  53759a2ecddad2bb87a079a1f1519f73      ferramentas_jardim   
5822           1091  2b4609f8948be18874494203496bc318            beleza_saude   

       product_name_lenght  product_description_lenght  product_weight_g  \
9661                  54.0                       245.0            1383.0   
13430                 44.0                       903.0            2600.0   
14051                 56.0                       348.0            1550.0   
8290                  59.0                      1893.0            6550.0   
30293                 59.0                       341.0            1750.0   
793                   33.0                       523.0             584.0   
1749                  48.0                       575.0             100.0   
4598                  57.0                       366.0            1650.0   
32098                 58.0                       340.0            1500.0   
5822                  59.0                       492.0             250.0   

       product_length_cm  product_height_cm  product_width_cm  
9661                50.0               10.0              40.0  
13430               50.0               10.0              30.0  
14051               30.0               22.0              30.0  
8290                20.0               20.0              20.0  
30293               37.0               22.0              40.0  
793                 16.0               11.0              13.0  
1749                20.0               15.0              15.0  
4598                30.0               22.0              30.0  
32098               30.0               22.0              30.0  
5822                22.0               10.0              18.0

In [89]:
##Recomendando as Categorias com Maiores notas de Review
count2 = df1.groupby(by='product_category_name', as_index=False) \
  .agg({'order_id': pd.Series.nunique}) \
  .rename(columns={'order_id': 'Compras Realizadas'})

buy_count2 = count2.set_index('product_category_name')
top1500_vendas2 = buy_count2.sort_values('Compras Realizadas', ascending = False).head(1500)

top1500_vendas2.head(10)

Compras Realizadas
product_category_name                     
cama_mesa_banho                       9313
beleza_saude                          8771
esporte_lazer                         7669
informatica_acessorios                6649
moveis_decoracao                      6398
utilidades_domesticas                 5843
relogios_presentes                    5576
telefonia                             4168
automotivo                            3877
brinquedos                            3853

In [87]:
##Recomendando os Produtos Mais Populares
count = df1.groupby(by='product_id', as_index=False) \
  .agg({'order_id': pd.Series.nunique}) \
  .rename(columns={'order_id': 'Compras Realizadas'})

buy_count = count.set_index('product_id')
top1500_vendas = buy_count.sort_values('Compras Realizadas', ascending = False).head(1500)

top1500_vendas.merge(df_products_dataset, left_index = True,right_on = 'product_id').head(10)

Compras Realizadas                        product_id  \
9661                  458  99a4788cb24856965c36a24e339b6058   
13430                 429  aca2eb7d00ea1a7b8ebd4e68314663af   
14051                 351  422879e10f46682990de24d770e7f83d   
8290                  320  d1c427060a0f73f6b889a5c7c61f2ac4   
30293                 310  389d119b48cf3043d311335e499d9c6b   
793                   303  53b36df67ebb7c41585e8d54d6772e08   
4598                  289  368c6c730842d78016ad823897a372db   
32098                 285  53759a2ecddad2bb87a079a1f1519f73   
1749                  268  154e7e31ebfa092203795c972e5804a6   
5822                  259  2b4609f8948be18874494203496bc318   

        product_category_name  product_name_lenght  \
9661          cama_mesa_banho                 54.0   
13430        moveis_decoracao                 44.0   
14051      ferramentas_jardim                 56.0   
8290   informatica_acessorios                 59.0   
30293      ferramentas_jardim                 59.0   
793        relogios_presentes                 33.0   
4598       ferramentas_jardim                 57.0   
32098      ferramentas_jardim                 58.0   
1749             beleza_saude                 48.0   
5822             beleza_saude                 59.0   

       product_description_lenght  product_weight_g  product_length_cm  \
9661                        245.0            1383.0               50.0   
13430                       903.0            2600.0               50.0   
14051                       348.0            1550.0               30.0   
8290                       1893.0            6550.0               20.0   
30293                       341.0            1750.0               37.0   
793                         523.0             584.0               16.0   
4598                        366.0            1650.0               30.0   
32098                       340.0            1500.0               30.0   
1749                        575.0             100.0               20.0   
5822                        492.0             250.0               22.0   

       product_height_cm  product_width_cm  
9661                10.0              40.0  
13430               10.0              30.0  
14051               22.0              30.0  
8290                20.0              20.0  
30293               22.0              40.0  
793                 11.0              13.0  
4598                22.0              30.0  
32098               22.0              30.0  
1749                15.0              15.0  
5822                10.0              18.0

In [48]:
##Recomendando os produtos com maiores médias de review

df1.groupby(by='product_id', as_index=False) \
    .agg({'review_score': np.mean}) \
    .rename(columns={'review_score': 'review_score_avg'}) \
    .set_index('product_id') \
    .sort_values('review_score_avg', ascending = False)

review_score_avg
product_id                                        
00066f42aeeb9f3007548bb9d3f33c38               5.0
602be4713d609927aca6161cf5b45220               5.0
6004f0ea115c80b51e2f0e434233c0ca               5.0
60061c870d0d52a2c5bc678d56538fdd               5.0
600add16084eeeead5c56279ccef0d7e               5.0
...                                            ...
dea3de7c4e7aa375d564fa2ddb7099b7               1.0
368645a47a15770520ad12d9ea77c2f2               1.0
8a69fc3b5330f7b77ca1a290dfafb133               1.0
36856b22e842c96589a6b542aa92e179               1.0
a0b0fad03e38e8e5d6d94e229707f2ef               1.0

[32183 rows x 1 columns]

# Matriz de Similaridade

In [54]:
#Matriz de similaridade top_produtos - Quando o cliente estiver buscando o produto
matriz_de_relacionamento_top_produtos_ratings = df1[df1['product_id'].isin(top1500_product.index.to_list())] \
  .pivot_table(index='product_id', columns='customer_id', values="review_score").fillna(0)

matriz_de_relacionamento_top_produtos_ratings.shape

(1500, 40154)

In [57]:
cos_produtos = cosine_similarity(matriz_de_relacionamento_top_produtos_ratings)

print(cos_produtos)
cos_produtos.shape

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


(1500, 1500)

In [70]:
def recomendar(id_produto):
  print(f"Produto de interesse: {id_produto}")
  try:
    produto_idx = matriz_de_relacionamento_top_produtos_ratings.index.tolist().index(id_produto)
    closest_10_products = np.argsort(-cos_produtos[produto_idx])[1:11]
    print(f"Retornando 10 produtos mais próximos de: {id_produto}.")
    return matriz_de_relacionamento_top_produtos_ratings.index[closest_10_products].tolist()
  except ValueError as e:
    print(f"{id_produto}, não está incluso na matriz de recomendação. Retornando os 10 mais avaliados")
    return top1500_product.head(10)

In [73]:
id_produto_interesse = "99a4788cb24856965c36a24e339b6058"
ids_10_mais_proximos = recomendar(id_produto_interesse)

ids_10_mais_proximos

Produto de interesse: 99a4788cb24856965c36a24e339b6058
Retornando 10 produtos mais próximos de: 99a4788cb24856965c36a24e339b6058.


['35afc973633aaeb6b877ff57b2793310',
 'f2e53dd1670f3c376518263b3f71424d',
 '3e5201fe0d1ba474d9b90152c83c706c',
 '42a2bd596fda1baef5719cb74f73030c',
 '98b22c1129886cbd7fcae69d1c93e442',
 'eebbed5ed3b134eceb717496c47652ba',
 '9ad75bd7267e5c724cb42c71ac56ca72',
 'ace5d86cf1ac63cdb76f49e5cd23d2f8',
 'acde6bd0b5f91190e2a123df389b0b47',
 'acdd408fe971bbe29a81f8febb575ffc']

In [90]:
top1500_vendas2

Compras Realizadas
product_category_name                            
cama_mesa_banho                              9313
beleza_saude                                 8771
esporte_lazer                                7669
informatica_acessorios                       6649
moveis_decoracao                             6398
...                                           ...
la_cuisine                                     12
cds_dvds_musicais                              12
pc_gamer                                        8
fashion_roupa_infanto_juvenil                   8
seguros_e_servicos                              2

[73 rows x 1 columns]

In [96]:
#Matriz de similaridade top_produtos - Quando o cliente estiver buscando o produto e não achar - mesma categoria
buy_count3 = count.set_index('product_id')
top_pop = buy_count3.sort_values('Compras Realizadas', ascending = False)

pop_cat = top_pop.merge(df_products_dataset, left_index = True,right_on = 'product_id')

def recomendar_cat(product_id):
  print(f"Produto de interesse: {product_id}")
  try:
    categoria = pop_cat[pop_cat['product_id'] == product_id ]
    a = categoria['product_category_name'].to_list()
    
    df_aux = df_all[df_all["product_id"].isin(top1500_product.index.to_list())]
    matriz_de_relacionamento_top_products_pop = df_aux[df_aux['product_category_name'] == a[0] ] \
    .pivot_table(index="product_id", columns="customer_id", values="review_score").fillna(0)
    
    cos_products_cat = cosine_similarity(matriz_de_relacionamento_top_products_pop)
    
    product_idx = matriz_de_relacionamento_top_products_pop.index.tolist().index(product_id)
    closest_10_products_cat = np.argsort(-cos_products_cat[product_idx])[1:11]
    print(f"Retornando 10 produtos mais próximos de: {product_id}.")
    return matriz_de_relacionamento_top_products_pop.index[closest_10_products_cat].tolist()
  except ValueError as e:
    print(f"{product_id}, não está incluso na matriz de recomendação. Retornando os 10 mais avaliados")
    return pop_cat[pop_cat['product_category_name'] == a[0]].head(10)['product_id'].to_list()


In [101]:
id_product_interesse_cat = "35afc973633aaeb6b877ff57b2793310"
ids_10_mais_proximos_cat = recomendar_cat(id_product_interesse_cat)
ids_10_mais_proximos_cat

Produto de interesse: 35afc973633aaeb6b877ff57b2793310
Retornando 10 produtos mais próximos de: 35afc973633aaeb6b877ff57b2793310.


[]

In [102]:
categoria = pop_cat[pop_cat['product_id'] == '35afc973633aaeb6b877ff57b2793310' ]
a = categoria['product_category_name'].to_list()
a[0]

'casa_conforto'

# Transformando em Classe

In [109]:
class RecommendationSystem:

    def start_pipeline(dataf):
        return dataf.copy()

    def get_products_counts(dataf):
      return dataf.groupby(by='product_id', as_index=False) \
        .agg({'customer_id': pd.Series.nunique}) \
        .rename(columns={'customer_id': 'Customer_ID_count'}) \
        .set_index('product_id') \
        .sort_values('Customer_ID_count', ascending = False)

    def get_avg_ratings(dataf):
      return dataf.groupby(by='product_id', as_index=False) \
        .agg({'review_score': np.mean}) \
        .rename(columns={'review_score': 'review_score_avg'}) \
        .set_index('product_id') \
        .sort_values('review_score_avg', ascending = False)

    def get_n_top_values(dataf, n):
      return dataf.head(n) \
        .index \
        .tolist()

    top_products_ratings = df1 \
      .pipe(start_pipeline) \
      .pipe(get_avg_ratings) \
      .pipe(get_n_top_values, n=1500)

    top_products_sellers = df1 \
      .pipe(start_pipeline) \
      .pipe(get_products_counts) \
      .pipe(get_n_top_values, n=10)

In [105]:
top_products_ratings[:10], top_products_sellers

(['00066f42aeeb9f3007548bb9d3f33c38',
  '602be4713d609927aca6161cf5b45220',
  '6004f0ea115c80b51e2f0e434233c0ca',
  '60061c870d0d52a2c5bc678d56538fdd',
  '600add16084eeeead5c56279ccef0d7e',
  '600dd8d6e08f57945bf0798abe1b1b5b',
  'c6e5e65a8d521761e0d1a4f6812fc2ea',
  '6016ec35b91d455a84929e2066601c01',
  '601d52789faa7ded8408d63ccfcb4800',
  '6020b332bb4a8888917d4844eba70bbe'],
 ['99a4788cb24856965c36a24e339b6058',
  'aca2eb7d00ea1a7b8ebd4e68314663af',
  '422879e10f46682990de24d770e7f83d',
  'd1c427060a0f73f6b889a5c7c61f2ac4',
  '389d119b48cf3043d311335e499d9c6b',
  '53b36df67ebb7c41585e8d54d6772e08',
  '368c6c730842d78016ad823897a372db',
  '53759a2ecddad2bb87a079a1f1519f73',
  '154e7e31ebfa092203795c972e5804a6',
  '2b4609f8948be18874494203496bc318'])

In [106]:
Recomm

review_score_avg
product_id                                        
00066f42aeeb9f3007548bb9d3f33c38               5.0
602be4713d609927aca6161cf5b45220               5.0
6004f0ea115c80b51e2f0e434233c0ca               5.0
60061c870d0d52a2c5bc678d56538fdd               5.0
600add16084eeeead5c56279ccef0d7e               5.0
...                                            ...
dea3de7c4e7aa375d564fa2ddb7099b7               1.0
368645a47a15770520ad12d9ea77c2f2               1.0
8a69fc3b5330f7b77ca1a290dfafb133               1.0
36856b22e842c96589a6b542aa92e179               1.0
a0b0fad03e38e8e5d6d94e229707f2ef               1.0

[32183 rows x 1 columns]

__main__.RecommendationSystem